job('First-Maven-Project-Via-DSL') {
    description("First Maven job generated by the DSL on ${new Date()}, the project is a small Maven project hosted on github")
    scm {
        git("https://github.com/Deria2017/Jenkins_Upgradev3.git", 'master')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean package', mavenName('Maven02'), 'maven-samples/single-module/pom.xml')
       
    }
    publishers {
        //archive the war file generated
        archiveArtifacts '**/*.jar'
    }
}
